import { Recipe } from './types';

// Built-in recipes served when SPOONACULAR_API_KEY is not set, so the app works
// end-to-end in local dev without a key. Images are stable remote URLs.
export const fixtureRecipes: Recipe[] = [
  {
    id: 'fx-spaghetti-carbonara',
    title: 'Spaghetti Carbonara',
    image: 'https://www.themealdb.com/images/media/meals/llcbn01574260722.jpg',
    sourceUrl: 'https://www.themealdb.com/meal/52982',
    sourceName: 'TheMealDB',
    readyInMinutes: 25,
    servings: 4,
    ingredients: [
      '400g spaghetti',
      '150g pancetta or guanciale, diced',
      '4 large egg yolks',
      '1 whole egg',
      '75g Pecorino Romano, grated',
      '50g Parmesan, grated',
      'Freshly cracked black pepper',
      'Salt, for pasta water',
    ],
    instructions: [
      'Bring a large pot of salted water to a boil and cook spaghetti until al dente.',
      'While pasta cooks, fry the pancetta in a large pan over medium heat until crisp.',
      'Whisk egg yolks, whole egg, Pecorino, and Parmesan together with black pepper.',
      'Reserve 1 cup of pasta water, then drain the pasta.',
      'Off the heat, toss the hot pasta with the pancetta, then quickly stir in the egg mixture, adding pasta water until creamy.',
      'Serve immediately with extra cheese and pepper.',
    ],
  },
  {
    id: 'fx-classic-guacamole',
    title: 'Classic Guacamole',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Guacamole_IMGP1271.jpg/960px-Guacamole_IMGP1271.jpg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Guacamole',
    sourceName: 'Fresh & Simple',
    readyInMinutes: 15,
    servings: 6,
    ingredients: [
      '3 ripe avocados',
      '1/2 red onion, finely diced',
      '2 Roma tomatoes, diced',
      '1 jalapeño, seeded and minced',
      '2 tbsp cilantro, chopped',
      '2 tbsp lime juice',
      'Salt, to taste',
    ],
    instructions: [
      'Halve the avocados, remove the pits, and scoop the flesh into a bowl.',
      'Mash to your desired consistency with a fork.',
      'Fold in onion, tomatoes, jalapeño, and cilantro.',
      'Stir in lime juice and season with salt.',
      'Taste, adjust, and serve with tortilla chips.',
    ],
  },
  {
    id: 'fx-chicken-tikka-masala',
    title: 'Chicken Tikka Masala',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Chicken_tikka_masala.jpg/960px-Chicken_tikka_masala.jpg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Chicken_tikka_masala',
    sourceName: 'Spice Route Kitchen',
    readyInMinutes: 50,
    servings: 4,
    ingredients: [
      '700g boneless chicken thighs, cubed',
      '1 cup plain yogurt',
      '2 tbsp lemon juice',
      '4 tsp garam masala, divided',
      '2 tsp cumin',
      '2 tsp paprika',
      '4 cloves garlic, minced',
      '1 tbsp fresh ginger, grated',
      '1 onion, diced',
      '400g canned crushed tomatoes',
      '1 cup heavy cream',
      'Fresh cilantro, for garnish',
    ],
    instructions: [
      'Marinate chicken in yogurt, lemon juice, 2 tsp garam masala, cumin, paprika, garlic, and ginger for at least 1 hour.',
      'Grill or pan-sear the chicken until charred and cooked through; set aside.',
      'Sauté onion until soft, then add remaining garam masala and cook until fragrant.',
      'Add crushed tomatoes and simmer for 10 minutes.',
      'Stir in cream and cooked chicken, simmering until the sauce thickens.',
      'Garnish with cilantro and serve with rice or naan.',
    ],
  },
  {
    id: 'fx-margherita-pizza',
    title: 'Margherita Pizza',
    image: 'https://www.themealdb.com/images/media/meals/x0lk931587671540.jpg',
    sourceUrl: 'https://www.themealdb.com/meal/53014',
    sourceName: 'TheMealDB',
    readyInMinutes: 40,
    servings: 2,
    ingredients: [
      '1 pizza dough ball',
      '1/2 cup San Marzano tomato sauce',
      '150g fresh mozzarella, torn',
      'Fresh basil leaves',
      '2 tbsp olive oil',
      'Salt, to taste',
    ],
    instructions: [
      'Preheat the oven (with a pizza stone if available) to its highest setting.',
      'Stretch the dough into a round on a floured surface.',
      'Spread tomato sauce, leaving a border for the crust.',
      'Scatter torn mozzarella over the sauce.',
      'Bake until the crust is golden and cheese is bubbling, 8–12 minutes.',
      'Top with basil, a drizzle of olive oil, and a pinch of salt.',
    ],
  },
  {
    id: 'fx-beef-tacos',
    title: 'Beef Tacos',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Tacos_al_pastor.jpg/960px-Tacos_al_pastor.jpg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Taco',
    sourceName: 'Fresh & Simple',
    readyInMinutes: 30,
    servings: 4,
    ingredients: [
      '500g ground beef',
      '1 packet taco seasoning (or homemade blend)',
      '8 small corn tortillas',
      '1 cup shredded lettuce',
      '1 cup shredded cheddar',
      '1 tomato, diced',
      'Sour cream and salsa, to serve',
    ],
    instructions: [
      'Brown the ground beef in a skillet over medium-high heat, breaking it up as it cooks.',
      'Drain excess fat, then stir in taco seasoning and a splash of water; simmer 5 minutes.',
      'Warm the tortillas in a dry pan or over a flame.',
      'Fill each tortilla with beef, lettuce, cheese, and tomato.',
      'Top with sour cream and salsa and serve.',
    ],
  },
  {
    id: 'fx-greek-salad',
    title: 'Greek Salad',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e2/Horiatiki_salad.jpg/960px-Horiatiki_salad.jpg',
    sourceUrl: 'https://en.wikipedia.org/wiki/Greek_salad',
    sourceName: 'Mediterranean Table',
    readyInMinutes: 15,
    servings: 4,
    ingredients: [
      '4 tomatoes, cut into wedges',
      '1 cucumber, sliced',
      '1 green bell pepper, sliced',
      '1/2 red onion, thinly sliced',
      '150g feta, sliced or cubed',
      '1/2 cup Kalamata olives',
      '3 tbsp olive oil',
      '1 tbsp red wine vinegar',
      '1 tsp dried oregano',
    ],
    instructions: [
      'Combine tomatoes, cucumber, bell pepper, and onion in a bowl.',
      'Add olives and top with feta.',
      'Whisk olive oil, vinegar, and oregano, then drizzle over the salad.',
      'Season with salt and pepper and serve.',
    ],
  },
  {
    id: 'fx-banana-pancakes',
    title: 'Banana Pancakes',
    image: 'https://www.themealdb.com/images/media/meals/rwuyqx1511383174.jpg',
    sourceUrl: 'https://www.themealdb.com/meal/52855',
    sourceName: 'Weekend Brunch Co.',
    readyInMinutes: 20,
    servings: 3,
    ingredients: [
      '1 1/2 cups flour',
      '2 tbsp sugar',
      '2 tsp baking powder',
      '1/2 tsp salt',
      '1 1/4 cups milk',
      '1 egg',
      '2 ripe bananas, mashed',
      '2 tbsp melted butter',
      'Maple syrup, to serve',
    ],
    instructions: [
      'Whisk flour, sugar, baking powder, and salt together.',
      'In another bowl, mix milk, egg, mashed banana, and melted butter.',
      'Combine wet and dry until just mixed (a few lumps are fine).',
      'Cook 1/4-cup portions on a greased griddle until bubbles form, then flip.',
      'Cook until golden and serve warm with maple syrup.',
    ],
  },
  {
    id: 'fx-thai-green-curry',
    title: 'Thai Green Curry',
    image: 'https://www.themealdb.com/images/media/meals/sstssx1487349585.jpg',
    sourceUrl: 'https://www.themealdb.com/meal/52921',
    sourceName: 'Spice Route Kitchen',
    readyInMinutes: 35,
    servings: 4,
    ingredients: [
      '400ml coconut milk',
      '3 tbsp green curry paste',
      '500g chicken thighs, sliced',
      '1 eggplant, cubed',
      '1 red bell pepper, sliced',
      '2 kaffir lime leaves',
      '2 tbsp fish sauce',
      '1 tbsp brown sugar',
      'Thai basil leaves',
      'Cooked jasmine rice, to serve',
    ],
    instructions: [
      'Simmer a spoonful of thick coconut cream until fragrant oil separates.',
      'Stir in curry paste and fry until aromatic.',
      'Add chicken and cook until sealed.',
      'Pour in remaining coconut milk, then add eggplant, bell pepper, and lime leaves.',
      'Simmer until vegetables and chicken are cooked through.',
      'Season with fish sauce and sugar, finish with Thai basil, and serve over rice.',
    ],
  },
];

export function searchFixtures(query: string): Recipe[] {
  const tokens = query.trim().toLowerCase().split(/\s+/).filter(Boolean);
  if (!tokens.length) return fixtureRecipes;
  // Match a recipe if any query word appears in its title or ingredients, so a
  // spoken phrase like "chicken curry" still surfaces chicken and curry dishes.
  return fixtureRecipes.filter((r) => {
    const haystack = (r.title + ' ' + r.ingredients.join(' ')).toLowerCase();
    return tokens.some((t) => haystack.includes(t));
  });
}

export function getFixture(id: string): Recipe | undefined {
  return fixtureRecipes.find((r) => r.id === id);
}
